services:
  - type: web
    name: renart-product-api
    env: dotnet
    buildCommand: dotnet build
    startCommand: dotnet run
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT 